### ISSUE TITLE
Problems when running subprocess calls on Alpine target systems (symbol not found)

### ISSUE THREAD

**Issue by Gerrit91** [JonathonReinhart/staticx#143] opened 2020-08-17 10:12 UTC
Hi, there.

First of all: This project is cool! Thanks for coming up with something like this. :)

I have a Python application that I bundle with PyInstaller and then run through staticx. Everything runs pretty well except when the application wants to execute a subprocess call on an Alpine-based Docker container.

The application expects `git` to be installed on the target system. It actually works when running from `ubuntu` docker containers or from `centos:7`. But when running from an Alpine docker container, the following error occurs:
 
```
Error: Command returned with exit code 127: git version, stderr: Error relocating /tmp/_MEIZccKdL/libz.so.1: crc32_z: symbol not found
Error relocating /tmp/_MEIZccKdL/libz.so.1: __snprintf_chk: symbol not found
Error relocating /tmp/_MEIZccKdL/libz.so.1: __vsnprintf_chk: symbol not found
```

So... for some reason, it looks like `git` seems not to execute anymore (because this error message comes from stderr) when being executed through the application context. Is staticx running an application called by subprocess through another library context than the actual system context? Is there anything special that I need to know when running subprocess with staticx?

Some additional information:
- Application build is done in a Dockerfile [here](https://github.com/fi-ts/docker-make/blob/master/ci-build/Dockerfile)
- The binary can be downloaded from https://github.com/fi-ts/docker-make/releases/tag/v0.3.5
- You can reproduce the issue when installing the application on the `docker` base image, which is Alpine based (Docker is required on your host system):
    ```
   $ docker run --rm -it --entrypoint sh -w /workdir -v /var/run/docker.sock:/var/run/docker.sock docker
   /workdir #  apk add wget ca-certificates git
   /workdir #  wget -O /usr/local/bin/docker-make https://github.com/fi-ts/docker-make/releases/download/v0.3.5/docker-make-linux-amd64
   /workdir #  chmod +x /usr/local/bin/docker-make
   /workdir #  echo "FROM ubuntu" > Dockerfile
   /workdir #  docker-make --no-lint
   Error: Command returned with exit code 127: git version, stderr: Error relocating /tmp/_MEI0ki0d8/libz.so.1: crc32_z: symbol not found
   Error relocating /tmp/_MEI0ki0d8/libz.so.1: __snprintf_chk: symbol not found
   Error relocating /tmp/_MEI0ki0d8/libz.so.1: __vsnprintf_chk: symbol not found
   ```

**Comment by JonathonReinhart** [comment] 2020-08-17 12:02
Hi @Gerrit91,

First, what version of staticx are you using? The most recent version, [v0.11.0](https://github.com/JonathonReinhart/staticx/releases/tag/v0.11.0) made some pretty important changes that I wouldn't expect to cause a problem like this, but could have.

Second, I don't expect to gain much more information, but can you try running staticx with the `--debug` flag when you build? Not only will that output debug information at *build-time*, but it also includes a debug version of the supporting binaries which will output debug info at *run-time*.

---

```
Error: Command returned with exit code 127: git version, stderr: Error relocating /tmp/_MEIZccKdL/libz.so.1: crc32_z: symbol not found
Error relocating /tmp/_MEIZccKdL/libz.so.1: __snprintf_chk: symbol not found
Error relocating /tmp/_MEIZccKdL/libz.so.1: __vsnprintf_chk: symbol not found
```

This definitely looks like the dynamic loader, when trying to load `git`, is trying to load `libz.so` from the PyInstaller bundle directory, and not from the system. That is unexpected, especially because it doesn't appear to involve staticx. Am I correct in assuming that this does not happen if PyInstaller is used without staticx?

> Is staticx running an application called by subprocess through another library context than the actual system context?

Not really. Staticx, at build time, modifies the user program's ELF headers, so that when the dynamic loader runs, the library path is constrained to to the directory where the staticx bootloader has dumped everything out. However, this should only apply to the user program (in this case your PyInstalled app).

To my knowledge, there is no mechanism which would extend that behavior to another child process. It is possible however, that there is some difference between GLIBC and musl-libc (which Alpine uses) that I'm not understanding.

I'll take a look at your program and see if anything stands out.

**Comment by Gerrit91** [comment] 2020-08-17 15:53
Thanks for this quick response!

I am using v0.11.0 indeed. I've now instructed the build to be run with the `--debug` flag for both PyInstaller and staticx. One can see that PyInstaller adds libz.so to the bundle:

```
4089 DEBUG: Adding libz.so.1 dependency of python3.8 from /lib/x86_64-linux-gnu/libz.so.1
```

staticx also sees it in the archive: 

```
DEBUG:root:libz.so.1 already in pyinstaller archive
```

Here are the entire build logs (just expand the `Build Linux` step): https://github.com/fi-ts/docker-make/runs/994228754?check_suite_focus=true

> Am I correct in assuming that this does not happen if PyInstaller is used without staticx?

Yep. At the moment, I am building the binary on Ubuntu. If I just run the binary from PyInstaller without involving staticx, it works fine on Ubuntu. Of course, on Alpine the binary cannot be executed at all with `not found` because it was bundled against glibc with PyInstaller. Vice versa, if I build the binary with PyInstaller on Alpine, it works on Alpine but not on Ubuntu, which is why I started with staticx in the first place. :) 

I also tried building on Python 3.7 because I read that PyInstaller is not particularly ready for Python 3.8, but the problem remains the same.

**Comment by JonathonReinhart** [comment] 2020-08-18 01:53
Okay, I figured out the problem. Luckily for me it has nothing to do with Staticx :smile:

The problem is that PyInstaller (specifically, the bootloader) sets `LD_LIBRARY_PATH` before invoking your application. This is what caused `git` to try to load the `libz.so` from `/tmp/_MEIxxxxxx`.

The PyInstaller docs cover this exact issue: [LD_LIBRARY_PATH / LIBPATH considerations](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations). (The doc update seems to have followed https://github.com/pyinstaller/pyinstaller/issues/1759).

So you'll need to follow the recipe provided there, to ensure `LD_LIBRARY_PATH` is cleared, (or set to `LD_LIBRARY_PATH_ORIG`, if present) in the environment that you pass to your `subprocess` calls.

I'm closing this issue since it's not a Staticx bug. But feel free to ping me on a `docker-make` issue/PR if you have any trouble getting it working. Good luck!

**Closed by JonathonReinhart** 2020-08-18 01:53 UTC
Labels: needs investigation

**Comment by JonathonReinhart** [comment] 2020-08-18 01:58
For posterity, I confirmed this by taking [your Dockerfile](https://github.com/fi-ts/docker-make/blob/c25eaf45de0b180f267c2ee00ff42effaa242116/ci-build/Dockerfile) and applying it to a modified version my [test/pyinstall](https://github.com/JonathonReinhart/staticx/tree/01d44380cbc1fda22977b15843d3a418a88af3ee/test/pyinstall) mini-project.

**`Dockerfile`**:
```dockerfile
FROM ubuntu as builder
ENV BOOTLOADER_CC=musl-gcc
RUN apt update && apt install -y busybox musl musl-dev musl-tools liblzma-dev scons patchelf python3-pip git
WORKDIR /app
COPY . .
RUN python3 -m pip install staticx pyinstaller
RUN pyinstaller -F app.py \
 && staticx --debug /app/dist/app /app/dist/app-static \
 && /app/dist/app-static

FROM docker
RUN apk update \
 && apk add git
COPY --from=builder /app/dist/app-static /app
CMD ["/app"]
```

**`app.py`**
```python
import os
import sys
import pwd
import subprocess

def get_resource_dir():
    default = os.path.dirname(os.path.abspath(__file__))
    return getattr(sys, '_MEIPASS', default)
    
print("Hello {}! Resource dir: {}".format(
    pwd.getpwuid(os.getuid()).pw_name,
    get_resource_dir()),
)

print("Environment")
for k, v in os.environ.items():
    print("  {}: {!r}".format(k, v))

args = ['git', '--version']
print("About to run", args)
subprocess.call(args)

if 'LD_LIBRARY_PATH' in os.environ:
    print("Unsetting LD_LIBRARY_PATH")
    os.unsetenv('LD_LIBRARY_PATH')

print("About to run", args)
subprocess.call(args)
```

Note that I *would not* recommend simply un-setting `LD_LIBRARY_PATH` as I've shown above. The problem is that Python will lazily load modules at runtime, and if `LD_LIBRARY_PATH` is unset in the Python process, it may affect the behavior of the dynamic loader (`ld.so`).

**Comment by Gerrit91** [comment] 2020-08-18 08:02
Brilliant. This was resolving all the issues I had. 

I am still wondering why PyInstaller docs say that there is an `*_ORIG` path which I do not see, but it also works by just removing the library paths from the execution environment. 

Thanks a lot, @JonathonReinhart! :100:

**Comment by JonathonReinhart** [comment] 2020-08-18 10:55
> I am still wondering why PyInstaller docs say that there is an *_ORIG path which I do not see

I'm guessing they only set `LD_LIBRARY_PATH_ORIG` if `LD_LIBRARY_PATH` was already set when the app was launched.

Thanks for the interesting problem. This was helpful for me, because I wasn't aware of those PyInstaller doc notes, and that is good to know for any PyInstaller app.
